### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by thatrandomperson5** [haoyu234/buju#3]
Some documentation for this library, whether is be simply comments or auto-generated documentation would be appreciated. While using this library, it is rather hard to dig into the source code to find out what each thing does.

**Comment by haoyu234** [comment]
You are right, the original C implementation has a lot of comments in it, maybe I should copy all of them. My implementation is based on this with only minor changes.

If you encounter layout problems, you can try to export the layout file and then open `/assets/demo.html` to debug js. This is how I debug it now, because debugging nim is painful.
